server:
  port: 8083

spring:
  application:
    name: leaderboard-service

  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:leaderboard_db}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:shashwat@16}

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka/}

springdoc:
  api-docs:
    path: /api-docs

  swagger-ui:
    path: /swagger-ui.html