server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**

        - id: submission-service
          uri: lb://submission-service
          predicates:
            - Path=/api/contests/**,/api/problems/**,/api/submissions/**

        - id: leaderboard-service
          uri: lb://leaderboard-service
          predicates:
            - Path=/api/leaderboard/**

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka/}

jwt:
  secret: YOUR_SECRET

springdoc:
  api-docs:
    path: /api-docs

  swagger-ui:
    path: /swagger-ui.html