server:
  port: 8081

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:leaderboard_db}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:shashwat@16}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka/}

jwt:
  secret: YOUR_SECRET

default-admin:
  username: admin
  email: admin@example.com
  password: admin123

springdoc:
  api-docs:
    path: /api-docs

  swagger-ui:
    path: /swagger-ui.html