package com.leaderboard.submissionservice.service.impl;

import com.leaderboard.submissionservice.Exception.ProblemNotFoundException;
import com.leaderboard.submissionservice.domain.Problem;
import com.leaderboard.submissionservice.domain.Submission;
import com.leaderboard.submissionservice.domain.emun.SubmissionStatus;
import com.leaderboard.submissionservice.event.SubmissionCreatedEvent;
import org.springframework.context.ApplicationEventPublisher;
import com.leaderboard.submissionservice.dto.CreateSubmissionRequest;
import com.leaderboard.submissionservice.dto.JudgeResult;
import com.leaderboard.submissionservice.dto.SubmissionResponse;
import com.leaderboard.submissionservice.repository.ProblemRepository;
import com.leaderboard.submissionservice.repository.SubmissionRepository;
import com.leaderboard.submissionservice.service.JudgeService;
import com.leaderboard.submissionservice.service.SubmissionService;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

import java.util.List;
@Service
@RequiredArgsConstructor
@Slf4j
public class SubmissionServiceImpl implements SubmissionService {
    private final ApplicationEventPublisher eventPublisher;
    private final SubmissionRepository submissionRepository;
    //private final JudgeService judgeService;
    private final ProblemRepository problemRepository;
    private SubmissionResponse mapToResponse(Submission submission) {
        return SubmissionResponse.builder()
                .id(submission.getId())
                .userId(submission.getUserId())
                .username(submission.getUsername())
                .problemId(submission.getProblem().getId())
                .status(submission.getStatus())
                .score(submission.getScore())
                .build();
    }
    @Override
    public SubmissionResponse submitSolution(Long problemId, Long userId, String username, CreateSubmissionRequest request) {
        Problem problem= problemRepository.findById(problemId)
                .orElseThrow(()-> new ProblemNotFoundException("not found"));

        Submission submission=Submission.builder()
                .userId(userId)
                .username(username)
                .problem(problem)
                .code(request.getCode())
                .status(
                        SubmissionStatus.PENDING
                )
                .score(0)
                .build();
        Submission savedSubmission = submissionRepository.save(submission);
        eventPublisher.publishEvent(new SubmissionCreatedEvent(savedSubmission.getId()));
        log.info("Submission created {}", submission.getId());
        return mapToResponse(savedSubmission);
    }

    @Override
    public List<SubmissionResponse> getMySubmissions(Long userId) {
        return submissionRepository
                .findByUserId(userId)
                .stream()
                .map(this::mapToResponse)
                .toList();
    }

    @Override
    public List<SubmissionResponse> getProblemSubmissions(Long problemId) {
        return submissionRepository
                .findByProblemId(problemId)
                .stream()
                .map(this::mapToResponse)
                .toList();
    }
}
/*

        ▼ (1) Your service runs: eventPublisher.publishEvent(new SubmissionCreatedEvent(id))
 ┌───────────────────────────────────────────────┐
 │         SubmissionEventListener Proxy         │  <--- Injected & Managed by Spring
 │    (Generated by AsyncExecutionInterceptor)   │
 └───────────────────────────────────────────────┘
        │
        ├─► (2) Intercepts the call (Sees @Async on your handleSubmissionCreated method)
        ├─► (3) Packages your logic and submits a Runnable task to... ──► [ TaskExecutor Thread Pool ]
        │                                                                             │
        ▼ (4) Immediate Return to your Service                                        │
   [ Logs "Submission created" & returns API Response ]                              │
                                                                                      ▼ (5) Runs asynchronously
                                                                           ┌─────────────────────────────────────┐
                                                                           │     SubmissionEventListener         │
                                                                           │  (Your actual listener method runs) │
                                                                           └─────────────────────────────────────┘
 */