package com.leaderboard.submissionservice.service.impl;

import com.leaderboard.submissionservice.Exception.ProblemNotFoundException;
import com.leaderboard.submissionservice.domain.Problem;
import com.leaderboard.submissionservice.domain.ScoreEvent;
import com.leaderboard.submissionservice.domain.Submission;
import com.leaderboard.submissionservice.domain.emun.SubmissionStatus;


import com.leaderboard.submissionservice.dto.Request.CreateSubmissionRequest;
import com.leaderboard.submissionservice.dto.Response.SubmissionResponse;
import com.leaderboard.submissionservice.dto.Result.JudgeResult;
import com.leaderboard.submissionservice.kafka.SubmissionEventProducer;
import com.leaderboard.submissionservice.repository.ProblemRepository;
import com.leaderboard.submissionservice.repository.SubmissionRepository;
import com.leaderboard.submissionservice.service.JudgeService;
import com.leaderboard.submissionservice.service.SubmissionService;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

import java.util.List;
@Service
@RequiredArgsConstructor
@Slf4j
public class SubmissionServiceImpl implements SubmissionService {

    private final SubmissionRepository submissionRepository;
    private final JudgeService judgeService;
    private final SubmissionEventProducer submissionEventProducer;
    private final ProblemRepository problemRepository;
    private SubmissionResponse mapToResponse(Submission submission) {
        return SubmissionResponse.builder()
                .id(submission.getId())
                .userId(submission.getUserId())
                .username(submission.getUsername())
                .problemId(submission.getProblem().getId())
                .status(submission.getStatus())
                .score(submission.getScore())
                .build();
    }
    @Override
    public SubmissionResponse submitSolution(Long problemId, Long userId, String username, CreateSubmissionRequest request
    ) {

        Problem problem = problemRepository.findById(problemId).orElseThrow(() -> new ProblemNotFoundException("Problem not found"));

        JudgeResult result = judgeService.judge(request.getCode());

        Submission submission = Submission.builder()
                        .problem(problem)
                        .userId(userId)
                        .username(username)
                        .code(request.getCode())
                        .status(result.getStatus())
                        .score(result.getScore())
                        .build();
        Submission savedSubmission = submissionRepository.save(submission);
        ScoreEvent scoreEvent = ScoreEvent.builder()
                        .submissionId(savedSubmission.getId())
                        .contestId(problem.getContest().getId())
                        .problemId(problem.getId())
                        .userId(userId)
                        .username(username)
                        .score(result.getScore())
                        .status(result.getStatus().name())
                        .build();
        submissionEventProducer.publish(scoreEvent);
        log.info("Submission {} processed", savedSubmission.getId());
        return mapToResponse(savedSubmission);
    }

    @Override
    public List<SubmissionResponse> getMySubmissions(Long userId) {
        return submissionRepository
                .findByUserId(userId)
                .stream()
                .map(this::mapToResponse)
                .toList();
    }

    @Override
    public List<SubmissionResponse> getProblemSubmissions(Long problemId) {
        return submissionRepository
                .findByProblemId(problemId)
                .stream()
                .map(this::mapToResponse)
                .toList();
    }
}
/*

        ▼ (1) Your service runs: eventPublisher.publishEvent(new SubmissionCreatedEvent(id))
 ┌───────────────────────────────────────────────┐
 │         SubmissionEventListener Proxy         │  <--- Injected & Managed by Spring
 │    (Generated by AsyncExecutionInterceptor)   │
 └───────────────────────────────────────────────┘
        │
        ├─► (2) Intercepts the call (Sees @Async on your handleSubmissionCreated method)
        ├─► (3) Packages your logic and submits a Runnable task to... ──► [ TaskExecutor Thread Pool ]
        │                                                                             │
        ▼ (4) Immediate Return to your Service                                        │
   [ Logs "Submission created" & returns API Response ]                              │
                                                                                      ▼ (5) Runs asynchronously
                                                                           ┌─────────────────────────────────────┐
                                                                           │     SubmissionEventListener         │
                                                                           │  (Your actual listener method runs) │
                                                                           └─────────────────────────────────────┘
 */